Removing truncate flag
uutils/coreutils pull request #1595
Opened 2020-09-06 05:15 UTC by chadbrewbaker

The  std::fs::File::create() method calls std::fs::OpenOptions::new().truncate(true). There is no good reason to set the truncate flag.

2020-09-06 16:05 UTC, rivy commented
I'm open to this change, but I'm hesitant to sign off without more information first.

Given my experience that the `rust` implementation group, most commonly, have good reason for everything that they do, I'd like to know why they coded the standard `File::create()` to truncate. It would help understand the implications (if any) of this change.

And, does this actually fix anything? If it doesn't fix a problem, we're adding a minor complexity wart without any return.

2020-09-06 16:07 UTC, rivy requested changes
As noted in the main line commentary, we need more information about the need/consequences of this change before adding a more complex statement in place of the standard `File::create(...)`.

2020-09-07 17:05 UTC, chadbrewbaker commented
See https://github.com/rust-lang/rust/blob/08deb863bdebfcbbb71c18acf903eca84f1df4e7/library/std/src/fs.rs#L339

```rust
 #[stable(feature = "rust1", since = "1.0.0")]
    pub fn create<P: AsRef<Path>>(path: P) -> io::Result<File> {
        OpenOptions::new().write(true).create(true).truncate(true).open(path.as_ref())
    }
```

File::create() has the unwanted behavior of truncation which could lead to data loss.    touch would never want to truncate an existing file. The OpenOptions API is stable.

2020-09-07 18:28 UTC, sylvestre commented on src/uu/touch/src/touch.rs
> +            if let Err(e) = std::fs::OpenOptions::new().write(true).create(true).open(path) {
Could you please add a comment explain the why?
thanks

2020-09-07 18:28 UTC, sylvestre commented
I guess it would be too hard to have a test for this?

2020-09-07 19:50 UTC, chadbrewbaker commented
Hmm. A testing framework expectation on truncate(true) not being called or a Linux only eBPF or strace test that checks for the truncate flag. I’ll research the test framework expectation as I am still a Rust noob and want to learn how anyway. Also writing a larger PR that adds a Readme.md that documents specs that need written, failing GNU tests, and a taxonomy of touch from various Unixes.

2020-09-10 03:11 UTC, rivy commented
A nice test to have for `touch` would be to stat an existing file, `touch` it, and then check to see that nothing except the modification times had been changed (size, permissions, etc).

2020-09-14 15:02 UTC, chadbrewbaker commented
I'm adding the GNU test suite tests, sorry it's taking so long.

2020-10-17 08:09 UTC, sylvestre commented
@chadbrewbaker do you have an update on this? thanks

2020-10-17 17:34 UTC, chadbrewbaker commented
Sorry, new client that took all my free time for a month. I should have a PR with failing touch GNU test suite cases (most turned off for features we aren't supporting), and some eBPF tests (giving an eBPF talk to Central Iowa Linux User Group next week).

2021-01-19 10:53 UTC, sylvestre commented
I will close it for now. Please reopen when ready!

2021-01-19 10:53 UTC, closed without merging