ptx: Improve performance: remove N^2 loop and reduce repetitive regex compilations.
uutils/coreutils pull request #1602
Opened 2020-10-09 09:51 UTC by wishawa

Fixes #1588 

## Benchmarks:
Release build on Linux on a quad core Intel CPU.

File: [http://textfiles.com/stories/aesop11.txt](http://textfiles.com/stories/aesop11.txt) (220 kB).
(empty lines were removed because GNU ptx -G couldn't handle them)
### The file as downloaded:
#### uutils ptx before my patch
```
user@8355880ef1c2:~/Rust-Projects/uutils$ time ./uu-ptx-old -G long_text_with_newlines.txt > /dev/null

real	0m1.335s
user	0m1.323s
sys	0m0.008s
```
#### uutils ptx with my patch
```
user@8355880ef1c2:~/Rust-Projects/uutils$ time ./uu-ptx-new -G long_text_with_newlines.txt > /dev/null

real	0m0.083s
user	0m0.077s
sys	0m0.006s
```
#### GNU ptx on Fedora 32
```
user@8355880ef1c2:~/Rust-Projects/uutils$ time ptx -G long_text_with_newlines.txt > /dev/null

real	0m0.038s
user	0m0.034s
sys	0m0.004s
```
### The file with newlines removed:
#### uutils ptx before my patch
```
user@pc:~/Rust-Projects/uutils$ time ./uu-ptx-old -G long_text_without_newlines.txt > /dev/null

real	0m28.478s
user	0m28.325s
sys	0m0.008s
```
#### uutils ptx with my patch
```
user@pc:~/Rust-Projects/uutils$ time ./uu-ptx-new -G long_text_without_newlines.txt > /dev/null

real	0m0.111s
user	0m0.099s
sys	0m0.010s
```
#### GNU ptx on Fedora 32
```
user@pc:~/Rust-Projects/uutils$ time ptx -G long_text_without_newlines.txt > /dev/null

real	0m0.041s
user	0m0.037s
sys	0m0.003s
```

2020-10-09 11:55 UTC, wishawa commented
I'm still a beginner in Rust, so if I'm doing anything wrong or unidiomatic, please do tell!

2020-10-11 17:11 UTC, rivy commented
@wishawa , thanks for the contribution!

The story is a bit hard to follow here ... This looks like only three changes to the original code base, so to help me review this, please squash the "fixes" for your additions into the original commit. For my initial investigation, it looks like the first five should likely be a single commit. And then that commit could be separated into the regex change and the loop change.

As for actual code critique, it appears that `WS_REG` (and the associated `lazy_static` package) aren't needed. The relevant regex (`config.context_regex`) that could be used to separate content within the line is already included in the configuration information passed to the `read_input` function.

If you'll make those changes, I'll look back at this more closely.

Thanks again.

2020-10-11 19:07 UTC, wishawa commented
Sorry for the messy commits 😅. I've force pushed the reorganized version over.

For WS_REG, my understanding is it is not the same thing as context_regex. I believe it is used to replace whitespace characters with plain space " ". But is_whitespace() does that anyway so I say we just remove it.

(There is probably some small performance gain to be had by replacing all whitespaces with plain space and only comparing against it, but let's do that later)

2021-03-20 10:09 UTC, sylvestre requested changes
Some minor nits. the code would benefit to get more comments!

It would be nice to add a few more tests too

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +        let chars_lines: Vec<Vec<char>> = lines.iter().map(|x| x.chars().collect()).collect();
please add a comment explaining what it is doing

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +fn create_word_set(config: &Config, filter: &WordFilter, file_map: &FileMap) -> BTreeSet<WordRef> {
please document this function

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +    let max_after_size = cmp::max(
please add a comment explaining that it is doing

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +    let mut bb_tmp = cmp::max(be as isize - max_before_size as isize, 0) as usize;
please add a comment explaining that this block is doing

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +    let max_head_size = cmp::max(
same here
please add a comment explaining that this block is doing

2021-03-20 10:09 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +fn format_tex_field(s: &str) -> String {
please document the function

2021-04-06 13:47 UTC, wishawa commented
Commit 5fc007b295230730bb2b67d3db32fb7defcac6a3 removes a code that I added to try to mimic GNU ptx's behavior.
This is because I believe that the GNU version just has too many "quirks" and if we try to replicate all of them we would end up rewriting their C code in Rust line by line.
Let me know what you think.

2021-04-06 18:55 UTC, sylvestre commented on src/uu/ptx/src/ptx.rs
> +            .value_of(options::FLAG_TRUNCATION)
do you think you could add a test to cover this case? thanks

2021-04-07 20:02 UTC, sylvestre commented
Testing it, I just found this bug:
https://github.com/uutils/coreutils/issues/2049

2021-04-07 21:13 UTC, sylvestre commented
hyperfine confirms your improvemens
```
hyperfine --warmup 2 --max-runs 10 'cp  sample.txt.orig sample.txt &&  /tmp/coreutils-old ptx -G sample.txt  > /dev/null' 'cp  sample.txt.orig sample.txt && ptx -G sample.txt > /dev/null' 'cp  sample.txt.orig sample.txt && ~/dev/debian/coreutils/target/release/coreutils ptx -G sample.txt  > /dev/null'
Benchmark #1: cp  sample.txt.orig sample.txt &&  /tmp/coreutils-old ptx -G sample.txt  > /dev/null
  Time (mean ± σ):      1.353 s ±  0.028 s    [User: 1.339 s, System: 0.010 s]
  Range (min … max):    1.302 s …  1.398 s    10 runs
 
Benchmark #2: cp  sample.txt.orig sample.txt && ptx -G sample.txt > /dev/null
  Time (mean ± σ):      29.9 ms ±   0.8 ms    [User: 28.8 ms, System: 1.1 ms]
  Range (min … max):    28.9 ms …  31.5 ms    10 runs
 
Benchmark #3: cp  sample.txt.orig sample.txt && ~/dev/debian/coreutils/target/release/coreutils ptx -G sample.txt  > /dev/null
  Time (mean ± σ):      93.6 ms ±   1.2 ms    [User: 85.3 ms, System: 8.3 ms]
  Range (min … max):    92.0 ms …  95.2 ms    10 runs
 
Summary
  'cp  sample.txt.orig sample.txt && ptx -G sample.txt > /dev/null' ran
    3.13 ± 0.09 times faster than 'cp  sample.txt.orig sample.txt && ~/dev/debian/coreutils/target/release/coreutils ptx -G sample.txt  > /dev/null'
   45.23 ± 1.50 times faster than 'cp  sample.txt.orig sample.txt &&  /tmp/coreutils-old ptx -G sample.txt  > /dev/null'
```

2021-04-07 21:14 UTC, merged

2021-04-07 21:14 UTC, sylvestre commented
Well done :)