refactor(users): move to clap and simplify the code a bit
uutils/coreutils pull request #1616
Opened 2020-10-25 14:32 UTC by sylvestre

2020-10-25 15:33 UTC, rivy requested changes
Nits, otherwise 👍 .

2020-10-25 15:33 UTC, rivy commented on src/uu/users/src/users.rs
> +static ABOUT: &str = "Output who is currently logged in according to FILE.";
Nit; attempting more consistency between uutils and slightly better? grammar/clarity.

```suggestion
static ABOUT: &str = "Display who is currently logged in, according to FILE.";
```

2020-10-25 15:33 UTC, rivy commented on src/uu/users/src/users.rs
> +    format!("{0} [FILE]...", executable!())
```suggestion
    format!("{0} [FILE]", executable!())
```
Only one is allowed.

2020-11-02 20:10 UTC, sylvestre commented
I am planning to land this Thursday 5st if no objection!

2020-11-02 21:35 UTC, rivy approved these changes

2020-11-03 07:37 UTC, merged