refactor(wc): use clap instead of getopts
uutils/coreutils pull request #1618
Opened 2020-10-25 18:34 UTC by sylvestre

2020-11-02 20:10 UTC, sylvestre commented
I am planning to land this Thursday 5st if no objection!

2020-11-02 21:33 UTC, rivy requested changes

2020-11-02 21:33 UTC, rivy commented on src/uu/wc/src/wc.rs
> +static ABOUT: &str = "print newline, word, and byte counts for each file.";
```suggestion
static ABOUT: &str = "Display newline, word, and byte counts for each FILE, and a total line if
more than one FILE is specified.";
```

More `coreutils` standard and GNU similar?

2020-11-03 00:39 UTC, rivy approved these changes

2020-11-03 08:39 UTC, merged