refactor(printenv): use clap instead of getopts
uutils/coreutils pull request #1620
Opened 2020-10-25 20:54 UTC by sylvestre

2020-11-02 20:10 UTC, sylvestre commented
I am planning to land this Thursday 5st if no objection!

2020-11-02 21:25 UTC, rivy requested changes
Minor ABOUT change request.

2020-11-02 21:25 UTC, rivy commented on src/uu/printenv/src/printenv.rs
> +static ABOUT: &str = "Prints the given environment VARIABLE(s), otherwise prints them all.";
```suggestion
static ABOUT: &str = "Display the values of the specified environment VARIABLE(s), or (with no VARIABLE) display name and value pairs for them all.";
```

Slightly more precise wording, similar to use elsewhere in `coreutils` and closer to GNU about text.

2020-11-03 00:37 UTC, rivy approved these changes

2020-11-03 07:36 UTC, merged