refactor(stat): Move to clap
uutils/coreutils pull request #1621
Opened 2020-10-28 22:54 UTC by sylvestre

2020-11-02 20:11 UTC, sylvestre commented
I am planning to land this Thursday 5st if no objection!

2020-11-02 21:12 UTC, rivy requested changes
One minor capitalization nit and needs `cargo fmt`. Otherwise, good to go.

2020-11-02 21:12 UTC, rivy commented on src/uu/stat/src/stat.rs
> +static ABOUT: &str = "display file or file system status.";
```suggestion
static ABOUT: &str = "Display file or file system status.";
```

2020-11-02 21:20 UTC, sylvestre commented
@rivy  Fixed! 
We don't show rusfmt warnings in the "Files changed" anymore?

2020-11-02 21:40 UTC, rivy commented
> We don't show rusfmt warnings in the "Files changed" anymore?

😕 That's where they showed up for me... it's a GitHub UI thing, not specifically a decision on our part. From my perspective, if/when we generate a GHA compatible warning with file and line number, it is showing up next to those lines when I look into the "Files changed" section. IMO, It's a helpful convenience since we can't really visibly surface warnings easily elsewhere at the moment.

2020-11-02 21:48 UTC, sylvestre commented
Bizarre, maybe I just missed it :)

2020-11-03 00:36 UTC, rivy approved these changes

2020-11-03 07:37 UTC, merged