refactor(rm): Move to clap + add a test
uutils/coreutils pull request #1632
Opened 2020-11-08 22:28 UTC by sylvestre

Will probably fail on some configurations because https://github.com/uutils/coreutils/pull/1629/commits/cc0a94ef7b486ce8a5c1554a82dcdfbb537b2ddd
needs to be merged first

2020-11-09 02:51 UTC, rivy commented
> Will probably fail on some configurations because [cc0a94e](https://github.com/uutils/coreutils/commit/cc0a94ef7b486ce8a5c1554a82dcdfbb537b2ddd)
> needs to be merged first

I got the same error; the fix is already included in the 'uucore' merge. Once that's merged, this can be rebased on top and it should work.

2020-11-09 09:11 UTC, sylvestre commented
I landed it here:
https://github.com/uutils/coreutils/pull/1633
to avoid the pain in the CI

2020-11-15 21:39 UTC, rivy requested changes
Minor nits.

2020-11-15 21:39 UTC, rivy commented on src/uu/rm/src/rm.rs
> +static OPT_VERBOSE: &str = "verbose";
Alphabetize as you can here...

2020-11-17 12:00 UTC, sylvestre commented
As it was only nit and the CI is green, I will land it now.

2020-11-17 12:00 UTC, merged