sleep: move from getopts to clap #1735
uutils/coreutils pull request #1777
Opened 2021-03-09 13:16 UTC by NotNorom

This commit replaces getopts with clap.
It does not introduce tests.

2021-03-09 19:18 UTC, sylvestre commented
Would you be interested in adding new tests?

just testing
```
sleep 0.1
sleep 0.1s
sleep 0.01m  
```

thanks

2021-03-10 16:19 UTC, NotNorom commented
I'll try!

2021-03-13 11:00 UTC, sylvestre requested changes
super close 
just needs tests :)

2021-03-13 21:59 UTC, sylvestre commented
Excellent, thanks :)

2021-03-13 22:10 UTC, sylvestre commented on tests/by-util/test_sleep.rs
> +}
Would be nice to also tests failure

like "sleep -2s"

but it can be done in a separate PR

2021-03-13 22:11 UTC, merged