date: Implement setting the date on Unix & Windows
uutils/coreutils pull request #1798
Opened 2021-03-11 05:40 UTC by marcosatti

Implements basic functionality for setting the date under both Unix & Windows systems.

Unresolved issues:
- `parse_date` only accepts limited formats for the dates input - separate issue needed?
- How are leap seconds handled on Windows? [Not immediately clear](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/support-for-leap-second), seems like they kind of ignore it which is what I've put in.

2021-03-11 08:37 UTC, sylvestre commented
It would be great to add tests too.
I guess it requires root but we could:
* test that the parsing of the input works
* test that the parsing of the input fails with the right error
* setting the date as not root fails the expected way :)

thanks

2021-03-11 12:22 UTC, marcosatti commented on src/uu/date/src/date.rs
> +use libc::{clock_settime, timespec, CLOCK_REALTIME};
Appears to be no way to set the clock on mac systems, so I'll go with disabling the feature like you said.

2021-03-11 17:21 UTC, sylvestre commented
Has some builds failures!

2021-03-12 04:03 UTC, marcosatti commented
> 
> 
> Has some builds failures!

Yeah not quite completed yet... 

The 32-bit platforms are still using `long` as `time_t`'s, so I'll jut add in a `try_into()` call - they should be updated by 2038 I would hope. The nanoseconds can fit into a i32 no matter what, so a static cast should be fine there.

2021-03-12 05:17 UTC, marcosatti commented
The gnu date always outputs the current date (regardless if there was a permissions error) when setting the date - do you want to create a new issue for this or should it be done in this one?

2021-03-12 07:22 UTC, marcosatti commented
Damn, try_into() was added in a later Rust version (v1.34?)... I'll just use a normal cast.

2021-03-12 22:13 UTC, sylvestre commented
please run
```
cargo +1.33.0 update
```

2021-03-13 10:56 UTC, sylvestre requested changes
only minor requests!
thanks

2021-03-13 10:56 UTC, sylvestre commented on src/uu/date/src/date.rs
> +fn make_platform_app<'a, 'b>(app: App<'a, 'b>) -> App<'a, 'b> {
I wonder if this isn't overkill ?
I think the option should also exist on mac but in the help section, add "not available on mac yet"
and this function should be added back in the main app declaration

2021-03-13 10:56 UTC, sylvestre commented on src/uu/date/src/date.rs
> +fn get_errno() -> i32 {
same, should not be declared for mac

2021-03-13 10:56 UTC, sylvestre commented on src/uu/date/src/date.rs
> +/// System call to set date (Windows).
thanks for the comments :)

2021-03-13 10:56 UTC, sylvestre commented on tests/by-util/test_date.rs
> +fn test_date_set_valid() {
please rustfmt

2021-03-17 21:05 UTC, sylvestre commented
@marcosatti ping?

2021-03-18 05:20 UTC, marcosatti commented
@sylvestre sorry been busy lately - will look at it later on in the week.

2021-03-19 08:53 UTC, sylvestre commented on src/uu/date/src/date.rs
> +    // TODO: The GNU date command can parse a wide variety of inputs.
In the tests, could you please add a case that GNU manages but we don't?

2021-03-19 08:54 UTC, merged

2021-03-19 08:54 UTC, sylvestre commented
Looks great :)
I will merge yet now, please open a PR for the last request!

2021-03-20 07:20 UTC, marcosatti commented
Created PR #1846 for more tests.