tests/tee: implemented tests for tee
uutils/coreutils pull request #1804
Opened 2021-03-11 23:38 UTC by jhscheer

These tests are ported from `https://github.com/coreutils/coreutils/tests/misc/tee.sh`.

Issue #1793 asked to add tests for tee.
There are tests in `tee.sh` that I could not port over because I don't know how to handle `timeouts` and `dd` in tests.

These are the tests I managed to port over:
- processing_multiple_operands
- treat_minus_as_filename
- append
- no_more_writeable_stdout
- no_more_writeable_stdin

The last two tests fail because rust's tee stdout/stderr differ from GNU's tee stdout/stderr if either of them is `/dev/full`.
I will open an issue for this.

2021-03-12 09:03 UTC, jhscheer commented
I forgot to mention.
There's a bug in write() which I fixed in PR #1802.
Meaning test_tee_append() will only succeed after this PR is merged.

2021-03-13 10:49 UTC, sylvestre commented
```
    test_tee::test_tee_no_more_writeable_stdin
    test_tee::test_tee_no_more_writeable_stdout
```
are still failing

2021-03-13 10:49 UTC, sylvestre requested changes
tests are failing

2021-03-13 13:05 UTC, jhscheer commented
@sylvestre 
Yes, it's correct that these two tests fail because there's a bug, see #1805

2021-03-26 12:07 UTC, jhscheer commented
@sylvestre I took out the failing tests until #1805 is fixed

2021-03-27 08:16 UTC, merged

2021-03-27 09:38 UTC, irymarchyk commented
@jhscheer , I am working on the fix for https://github.com/uutils/coreutils/issues/1805 and I have a question for your last test (test_tee_no_more_writeable_stdin). Test pipes in '/dev/full', but the example on the issue page does not have such example. AFAIK equal call to tee should be:
`tee out1 out2  < /dev/full` 
And I don't think that this test makes a lot of sense because /dev/full provides some data until the receiver is not full...

2021-03-27 10:38 UTC, jhscheer commented
@irymarchyk 
Yes you're right! 
That should've been a `pipe_out("/dev/full")` instead of `pipe_in("/dev/full")`.
However, I just looked at `tests/common/util.rs` and currently there's no `pipe_out()` implemented.
(The test names are also confusing, maybe `test_tee_no_more_writeable_1` and `test_tee_no_more_writeable_2` would be better.)
Summary:
The functionality I wanted to test in `test_tee_no_more_writeable_stdin` is `tee out1 out2 >/dev/full <multi_read`.