nice: move from getopts to clap #1794
uutils/coreutils pull request #1810
Opened 2021-03-12 20:44 UTC by jeckersb

2021-03-12 20:52 UTC, sylvestre reviewed
Well done, just some small nits !

2021-03-12 20:52 UTC, sylvestre commented on src/uu/nice/src/nice.rs
> +            Arg::with_name("adjustment")
For consistency with other binaries, please declare adjustment in a variable (or structure)

2021-03-12 20:52 UTC, sylvestre commented on src/uu/nice/src/nice.rs
> +        .arg(Arg::with_name("COMMAND").multiple(true))
ditto

2021-03-12 20:52 UTC, sylvestre commented on src/uu/nice/src/nice.rs
> +    let adjustment = match matches.value_of("adjustment") {
and update this :)

2021-03-12 20:52 UTC, sylvestre commented on tests/by-util/test_nice.rs
> +    let res = new_ucmd!().args(&["-n", "-1", "true"]).run();
thanks :)

2021-03-12 21:27 UTC, sylvestre commented on src/uu/nice/src/nice.rs
> +pub mod options {
Merci!

2021-03-12 22:08 UTC, sylvestre commented
This is failing on mac os, could you please fix this? thanks

2021-03-12 22:15 UTC, jeckersb commented
> This is failing on mac os, could you please fix this? thanks

Yeah I was just looking into that.  I don't have a macos system handy that I can test on.  But as far as I can tell from https://opensource.apple.com/source/shell_cmds/shell_cmds-17.1/nice/nice.1.auto.html, macos is using the netbsd version of nice.  So https://man.netbsd.org/nice.1 if you want something human-readable.  The main issue seems to be that the BSD version of nice doesn't seem to support running a bare "nice" without any arguments to display the current level of niceness.  So a lot of the tests are failing due to that.  But I think there's additional issues too beyond that.

I'll have to spin up a BSD VM to play around and that should be enough to approximate the behavior on macos, then I can sort out the differences there.

2021-03-13 10:52 UTC, sylvestre commented
You can always push changes in your github fork to debug remotely (not ideal :)

2021-03-13 10:52 UTC, sylvestre requested changes
mac failures

2021-03-15 17:36 UTC, jeckersb commented
Few updates here:

- I ditched the few tests that were doing some variation of "nice nice" because the 2nd invocation is dependent on the system version, and that's not really what we want to test anyway.
- I spun up a netbsd virtual machine, and the tests pass there.  Yay.
- I got my hands on a macbook, and... the tests also pass on the macbook???

At this point I am quite confused why the macos CI is failing.

2021-03-16 22:13 UTC, jeckersb commented
Finally figured this one out.  `nice` was checking `errno` after calling `getpriority`, but wasn't clearing `errno` beforehand.  When run inside of the test suite, some previous library call in another utility must have been setting `errno` and then the `getpriority` call was mistakenly being interpreted as failed.  No matter what arguments were supplied to `nice`, it would always fail with `ENOENT` (which isn't even a valid error for getpriority).  If `nice` was run standalone, it worked.  It also worked if the tests were invoked like `cargo test --features nice --no-default-features` because there was no prior library call to set `errno`.  The fact that this worked on platforms other than macos was just luck.

With that said, @sylvestre I think this is ready now.

2021-03-17 21:03 UTC, sylvestre approved these changes
well done!

2021-03-17 21:03 UTC, merged