pr: Implement this command
uutils/coreutils pull request #1918
Opened 2021-03-26 14:41 UTC by MaxSem

This PR is a resurrection of #1327 by @tilakpatidar.

Closes #1874

2021-03-26 17:48 UTC, sylvestre reviewed
it will take some time to review it but here is a few comments

2021-03-26 17:48 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +static NAME: &str = "pr";
Could you please follow this example to declarations the options?
https://github.com/uutils/coreutils/blob/master/src/uu/ls/src/ls.rs#L78-L80

2021-03-26 17:48 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +    let mut opts = getopts::Options::new();
Not blocker but it would be nice to use clap instead of getopts

2021-03-26 17:48 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +    //let a_file: Regex = Regex::new(r"^[^-+].*").unwrap();
please remove useless comments

2021-03-27 08:54 UTC, sylvestre requested changes
well done!

2021-03-27 08:54 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +fn print_usage(opts: &mut Options, matches: &Matches) -> i32 {
this can be removed when/if moved to clap

2021-03-27 08:54 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +        })
please add a test to cover this

2021-03-27 08:54 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +    let default_first_number: usize = NumberingMode::default().first_number;
same (test coverage)

2021-03-27 08:54 UTC, sylvestre commented on tests/common/util.rs
>      }
please run rustfmt

2021-03-27 08:54 UTC, sylvestre commented on tests/by-util/test_pr.rs
> +use crate::common::util::*;
please run rustfmt

2021-03-27 08:54 UTC, sylvestre commented on src/uu/pr/src/pr.rs
> +#![crate_name = "uu_pr"]
the file is quite long, maybe it would make sense to split it?

2021-04-05 20:26 UTC, sylvestre commented
@MaxSem ping?

2021-04-06 19:41 UTC, MaxSem commented
Sorry, was busy doing something else. Will try to find time in the next few days.

2021-04-25 21:29 UTC, sylvestre commented
@MaxSem  ping? :)

2021-05-07 08:36 UTC, sylvestre commented
@MaxSem ping? :)

2021-05-23 07:45 UTC, sylvestre commented
@MaxSem ping?

2021-05-30 07:14 UTC, sylvestre commented
moved to
https://github.com/uutils/coreutils/pull/2300

2021-05-30 07:14 UTC, closed without merging