nl: move from getopts to clap
uutils/coreutils pull request #1921
Opened 2021-03-26 18:44 UTC by LevitatingBusinessMan

For https://github.com/uutils/coreutils/issues/1864
There shouldn't be any behavioral changes.

2021-03-26 19:20 UTC, ycd requested changes
please run `rustfmt` to your code.

2021-03-26 19:20 UTC, ycd commented on src/uu/nl/src/nl.rs
> +            .value_name("")
I see that the existing implementation has empty value but GNU implementation has `NUMBER` for value name could you also add it?

```rust
       -i, --line-increment=NUMBER
              line number increment at each line
```

2021-03-27 07:42 UTC, ycd approved these changes
looks great, thanks!

2021-03-27 07:55 UTC, sylvestre commented
Indeed, thanks :)

2021-03-27 07:55 UTC, merged