sort: Add a GNU-style Random Sorter
uutils/coreutils pull request #1922
Opened 2021-03-26 19:05 UTC by electricboogie

The previous version was missing a GNU-style random sorter/shuffle ("-R").  I've implemented such a sorter and welcome your review.

2021-03-26 22:12 UTC, sylvestre commented on src/uu/sort/src/sort.rs
> +    rand_string
probably enough ?

```suggestion
    thread_rng()
        .sample_iter(&Alphanumeric)
        .take(16)
        .map(char::from)
        .collect::<String>()
```

2021-03-26 23:03 UTC, sylvestre requested changes

2021-03-26 23:03 UTC, sylvestre commented on src/uu/sort/src/sort.rs
> +use rand::{thread_rng, Rng};
please run rustfmt

2021-03-26 23:03 UTC, sylvestre commented on src/uu/sort/src/sort.rs
> +            random_shuffle(a, b, settings.salt.clone())
please add tests to have a proper code coverage

2021-03-27 08:14 UTC, sylvestre requested changes
Almost done, well done.
* it is great to have unit test but could you please add integration tests in:
https://github.com/uutils/coreutils/blob/master/tests/by-util/test_sort.rs
* please run "cargo +1.40.0 update" and amend Cargo.lock?

thanks

2021-03-27 15:07 UTC, electricboogie commented
Pleased to add integration tests.  Thanks.

2021-03-28 09:34 UTC, sylvestre commented on src/uu/sort/src/sort.rs
> +static OPT_RANDOM_SORT: &str = "random-sort";
```suggestion
```
Seems unused?

2021-03-28 09:35 UTC, sylvestre commented on tests/by-util/test_sort.rs
> +    for numeric_sort_param in vec!["-n", "--numeric-sort"] {
please run rustfmt

2021-03-28 09:35 UTC, sylvestre commented
```
 codecov/project Successful in 1s — 63.49% (+0.17%) compared to 0bdd61a 
```
Bravo :)

2021-03-29 09:54 UTC, sylvestre commented
Please rebase Cargo.lock  and it should be good :)

2021-03-29 11:05 UTC, merged