test: add tests and fixtures
uutils/coreutils pull request #1923
Opened 2021-03-26 22:19 UTC by ycd

Closes: https://github.com/uutils/coreutils/issues/1853

I'd also love to add a test with a file that has a slightly bigger byte-count, thought about running this with `scene_cmd!` with the following command `printf '\\%03o' $(seq 0500)'`  but i'm not sure how will it react the CI environment.

2021-03-27 07:55 UTC, sylvestre commented on tests/by-util/test_cksum.rs
> +        .fails()
please run rustfmt

2021-03-27 10:59 UTC, sylvestre commented
MinRust is failing:
```
---- test_cksum::test_arg_overrides_stdin stdout ----
current_directory_resolved: 
touch: /tmp/.tmpuDYKuQ/a
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils cksum a
thread 'test_cksum::test_arg_overrides_stdin' panicked at 'Broken pipe (os error 32)', tests/common/util.rs:574:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

2021-03-27 19:01 UTC, sylvestre commented
Fails on freebsd:
```
---- test_cksum::test_invalid_file stdout ----
current_directory_resolved: 
mkdir: /tmp/.tmpxqFke1/a
run: /tmp/cirrus-ci-build/target/debug/coreutils cksum a
thread 'test_cksum::test_invalid_file' panicked at 'assertion failed: !self.success', tests/common/util.rs:86:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You should display stderr/stdout

2021-03-28 08:36 UTC, sylvestre commented
On freebsd:
```


---- test_cksum::test_invalid_file stdout ----
current_directory_resolved: 
mkdir: /tmp/.tmpLie5OG/asdf
run: /tmp/cirrus-ci-build/target/debug/coreutils cksum asdf
"1160721993 512 asdf\n"
"1160721993 512 asdf\n"
thread 'test_cksum::test_invalid_file' panicked at 'assertion failed: result.stderr.contains(\"cksum: error: \'asdf\'\")', /tmp/cirrus-ci-build/tests/by-util/test_cksum.rs:61:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

2021-03-28 10:48 UTC, ycd commented
Once #1951 is merged, i will push another empty commit to retrigger tests :)

2021-03-31 08:35 UTC, Arcterus requested changes
Looks good to me otherwise.

2021-03-31 19:23 UTC, sylvestre commented
```
---- test_cksum::test_arg_overrides_stdin stdout ----

current_directory_resolved: 

touch: /tmp/.tmpzZBPJm/a

run: /home/travis/build/uutils/coreutils/target/debug/coreutils cksum a

thread 'test_cksum::test_arg_overrides_stdin' panicked at 'Broken pipe (os error 32)', tests/common/util.rs:733:37

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

failures:

    test_cksum::test_arg_overrides_stdin
```
fails

2021-04-01 20:15 UTC, ycd commented
I have no idea why do i get broken pipe sometimes, am i doing something wrong?

2021-04-01 21:11 UTC, sylvestre commented
> I have no idea why do i get broken pipe sometimes, am i doing something wrong?

Comment and disable the test for freebsd :)

2021-04-03 18:01 UTC, ycd commented
@sylvestre should i retrigger the CI with an empty commit?, CI fails for `ubuntu-18.04, i686-unknown-linux-gnu` fails for

2021-04-05 20:21 UTC, merged