csplit: move from getopts to clap
uutils/coreutils pull request #1995
Opened 2021-04-01 13:11 UTC by sivachandran

**with clap**
```bash
csplit 0.0.4
split a file into sections determined by context lines

USAGE:
    [OPTION]... FILE PATTERN...

FLAGS:
    -z, --elide-empty-files    remove empty output files
    -h, --help                 Prints help information
    -k, --keep-files           do not remove output files on errors
        --quiet                same as --silent
    -s, --silent               do not print counts of output file sizes
        --suppress-matched     suppress the lines matching PATTERN
    -V, --version              Prints version information

OPTIONS:
    -n, --digits <DIGITS>           use specified number of digits instead of 2
    -f, --prefix <PREFIX>           use PREFIX instead of 'xx'
    -b, --suffix-format <FORMAT>    use sprintf FORMAT instead of %02d

Output pieces of FILE separated by PATTERN(s) to files 'xx00', 'xx01', ..., and output byte counts of each piece to
standard output.
```
**with getopts**
```bash
$ ./target/debug/coreutils csplit --help

 csplit 0.0.4

 csplit [OPTION]... FILE PATTERN...

 split a file into sections determined by context lines

 Options:
        --help          print usage information
        --version       print name and version number
    -b, --suffix-format FORMAT
                        use sprintf FORMAT instead of %02d
    -f, --prefix PREFIX use PREFIX instead of 'xx'
    -k, --keep-files    do not remove output files on errors
        --suppress-matched
                        suppress the lines matching PATTERN
    -n, --digits DIGITS use specified number of digits instead of 2
    -s, --quiet         do not print counts of output file sizes
    -z, --elide-empty-files
                        remove empty output files

 Reference
Output pieces of FILE separated by PATTERN(s) to files 'xx00', 'xx01', ..., and output byte counts of each piece to standard output.
```

Addresses #1931

2021-04-01 15:17 UTC, jhscheer commented on src/uu/csplit/src/csplit.rs
>  static SYNTAX: &str = "[OPTION]... FILE PATTERN...";
The name of the application is missing.
The other ports use a function for that like so:
```rust
fn get_usage() -> String {                         
    format!("{} [OPTION]... FILE PATTERN...", executable!())
}                                                  
```

2021-04-01 15:22 UTC, jhscheer commented on src/uu/csplit/src/csplit.rs
> +                .help("same as --silent"),
No need for an extra `arg`, use https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.visible_alias instead.

2021-04-01 15:33 UTC, jhscheer commented on src/uu/csplit/src/csplit.rs
> +        show_error!("missing operand after '{}'", file_name);
clap should take care of these cases if you tell it which `.arg` are `required`, `required_unless`, etc.

2021-04-01 20:14 UTC, ycd commented on src/uu/csplit/src/csplit.rs
> +    if file_value.is_none() {
I think there is no need for this, afaik clap can handle this

2021-04-01 21:00 UTC, sylvestre requested changes
Just like the two other great reviewers did!

2021-04-02 13:14 UTC, sivachandran commented
@jhscheer @ycd Thanks for the review. Addressed the comments.

2021-04-02 20:14 UTC, sylvestre commented
great, thanks

2021-04-02 20:14 UTC, merged