kill: migrate to clap
uutils/coreutils pull request #2155
Opened 2021-05-01 15:03 UTC by nthery

- Migrate to clap.
- Change default signal to SIGTERM.
- Add integration tests.

Fixes #2122.

2021-05-01 17:11 UTC, sylvestre requested changes
well done for the tests :)
just some minor changes

2021-05-01 17:11 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +static OPT_PIDS_OR_SIGNALS: &str = "PID";
please use this syntax to declare the options

https://github.com/uutils/coreutils/search?q=%22pub+mod+options%22

2021-05-01 17:11 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +            Arg::with_name(OPT_LIST)
and use it here :)

2021-05-01 18:01 UTC, nthery commented on src/uu/kill/src/kill.rs
> +            Arg::with_name(OPT_LIST)
Ok.  Thx for the review.

2021-05-01 19:48 UTC, sylvestre requested changes
minor changes :)

2021-05-01 19:48 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +                .long("list")
```suggestion
                .long(options::LIST)
```

2021-05-01 19:48 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +                .long("table")
```suggestion
                .long(options::TABLE_NEW)
```

2021-05-01 19:48 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +                .long("signal")
```suggestion
                .long(options::SIGNAL)
```

2021-05-01 19:48 UTC, sylvestre commented on src/uu/kill/src/kill.rs
> +        .unwrap_or_default();
```suggestion
        .unwrap_or_default();

```

2021-05-02 16:45 UTC, sylvestre commented
Thanks to your patch, we are now about 70% code coverage! bravo :)
```Successful in 1s — 70.09% (+0.82%) ```

2021-05-02 16:45 UTC, merged