more: Show next file at bottom line
uutils/coreutils pull request #2357
Opened 2021-06-05 14:35 UTC by deantvv

Implement feature requested in #2318.

2021-06-05 17:37 UTC, tertsdiepraam requested changes
Awesome! It looks good, but I think the `itertools` dependency is not needed if you use `Peekable` from the standard library. Maybe something like this?
```rust
let mut files_iter = files.peekable();
while let (Some(file), next_file) = (files_iter.next(), files_iter.peek()) {
    let file = Path::new(file);
    let next_file = next_file.map(|&s| s);
}
```

2021-06-06 01:28 UTC, deantvv commented
> Awesome! It looks good, but I think the `itertools` dependency is not needed if you use `Peekable` from the standard library. Maybe something like this?
> 
> ```rust
> let mut files_iter = files.peekable();
> while let (Some(file), next_file) = (files_iter.next(), files_iter.peek()) {
>     let file = Path::new(file);
>     let next_file = next_file.map(|&s| s);
> }
> ```

Yes, this is really nicer than the stupid thing I did. Fix in new commit. Thank you.

2021-06-06 08:46 UTC, tertsdiepraam approved these changes

2021-06-06 08:50 UTC, tertsdiepraam commented
It was definitely not stupid! It actually looked quite nice and I would've accepted it if `more` already depended on `itertools`.

2021-06-06 08:52 UTC, merged