sort: fix `--key` argument handling
uutils/coreutils pull request #2403
Opened 2021-06-11 15:54 UTC by a-wai

When using `sort` with the `--key` option, all subsequent arguments
are considered its values, leading to failures such as:

  $ sort -t ":" -k 3 /etc/passwd
  sort: failed to parse key `/etc/passwd`: invalid option: `e`

This is a side-effect of having `multiple(true)` for this option,
as `multiple` supports separating values with either a comma or
whitespace. Therefore, as long as no other flag or option is
provided, all arguments following `-k` are treated like values
for this option.

Switching to `use_delimiter(true)` instead ensures only
comma-separated values are taken into account, and the following
arguments are properly interpreted.

2021-06-11 16:07 UTC, miDeb requested changes
Thanks for your contribution! This is indeed a bug in the current implementation. However, this is not the correct fix, as commas are a valid part of a key (`-k 1,2` means a key from field 1 to 2, inclusive). You can see that some tests are failing (to run tests, run `cargo test` in the `coreutils` directory).
As suggested [in the documentation for `multiple`](https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.multiple), i think the correct solution is to use `.multiple(true).number_of_values(1)`.
Could you also add a test (inside of https://github.com/uutils/coreutils/blob/master/tests/by-util/test_sort.rs) to make sure we don't regress this again?

2021-06-18 10:42 UTC, miDeb commented
@a-wai please let me know if you'd like to implement the change I suggested :)
If something wasn't clear feel free to ask

2021-06-18 11:38 UTC, a-wai commented
@miDeb yes, I'll handle it, although it might be a few more days before I can get to it.

(same with #2344, I have started looking into it but didn't find the time to finalize the needed changes yet)

2021-06-18 11:40 UTC, miDeb commented
No problem, please take your time :)

2021-07-06 11:29 UTC, miDeb commented
I took this over and implemented it in #2480.

2021-07-06 14:11 UTC, closed without merging