tail: handle `-` as an alias for stdin
uutils/coreutils pull request #2468
Opened 2021-06-29 17:52 UTC by thomasqueirozb

2021-06-30 21:11 UTC, sylvestre commented
please add a test to make sure that this is covered! thanks

2021-07-04 09:25 UTC, sylvestre requested changes
needs a test, should be easy to implement, see:
https://github.com/uutils/coreutils/blob/15da98d84e9a094ea72c5f51efcc2d8aa9e9184f/tests/by-util/test_wc.rs#L41-L48

2021-07-04 09:25 UTC, sylvestre commented on src/uu/tail/src/tail.rs
> +use std::os::unix::prelude::AsRawFd;
and please fix this warning :)

2021-07-10 08:38 UTC, sylvestre commented
@thomasqueirozb ping?

2021-07-10 19:52 UTC, thomasqueirozb commented
> @thomasqueirozb ping?

pong

2021-07-10 19:55 UTC, thomasqueirozb commented
I have been away from my computer the past week so I haven't been able to fix this. I will do this either tomorrow or the day after. Sorry for the delay

2021-07-13 07:56 UTC, sylvestre commented on src/uu/tail/src/tail.rs
> +    let stdin_string = String::from("standard input");
the compiler is complaining that
"unused variable: `stdin_string`"

2021-07-13 07:56 UTC, sylvestre commented on src/uu/tail/src/tail.rs
> +            {
maybe move this block into a dedicated function?

2021-07-31 08:29 UTC, sylvestre commented on src/uu/tail/src/tail.rs
> +use crate::platform::stdin_is_pipe_or_fifo;
could you please fix this warning?
```
unresolved import `crate::platform::stdin_is_pipe_or_fifo`
```

2021-08-01 21:22 UTC, thomasqueirozb commented
I hate conditional compilation... I can only see those messages after the CI runs

2021-08-01 22:24 UTC, merged

2021-08-29 19:31 UTC, jfinkels commented
Fixed #1323.