`tail`: obsolete syntax
uutils/coreutils pull request #2508
Opened 2021-07-20 15:49 UTC by tertsdiepraam

Closes https://github.com/uutils/coreutils/issues/2507.

2021-07-20 16:19 UTC, tertsdiepraam commented
MinRustV fails because of `strip_prefix`. This PR should wait until the version bump in https://github.com/uutils/coreutils/pull/2438 is merged, so that issue is resolved.

2021-07-21 21:23 UTC, miDeb requested changes
This is not fully correct:
> This obsolete form uses exactly one option and at most one file.

So we have to not treat it as the obsolete setting when there's more than one option or more than one file.

But, wow, all of these rules are so complicated and confusing :sweat_smile:

2021-07-21 21:23 UTC, miDeb commented on src/uu/tail/src/tail.rs
> +        let num = num_slice.parse::<usize>().unwrap();
Well, _technically_ this could fail if the number is too big.

2021-07-21 21:23 UTC, miDeb commented on src/uu/tail/src/tail.rs
> +                    _ => {}
We also have to return `false` if it is an invalid option.

2021-07-23 16:26 UTC, tertsdiepraam commented
@miDeb Thanks for your comments! I'll be able to continue working on this in about a week.

2021-07-27 13:14 UTC, miDeb commented
I was trying to implement the obsolete syntax for `sort`, however that doesn't seem to be possible with clap. I was thinking whether it would make sense to not support the obsolete syntax in all of our utilities, for consistency? Maybe supporting the obsolete syntax in some utilities only could be confusing?

2021-08-28 13:06 UTC, sylvestre commented
@tertsdiepraam any update on this ? thanks :)

2021-08-28 15:39 UTC, tertsdiepraam commented
Ah forgot about it😅 I'll fix this up in a few days.

2021-08-28 15:46 UTC, sylvestre commented
no worries ;)

2021-09-06 18:19 UTC, sylvestre commented
Did you see this warning?
```

error[E0658]: use of unstable library feature 'bool_to_option'
Error:    --> src/uu/tail/src/tail.rs:264:20
    |
264 |     char.is_none().then(|| ())
    |                    ^^^^
    |
    = note: see issue #64260 <https://github.com/rust-lang/rust/issues/64260> for more information
```

2021-09-30 12:41 UTC, tertsdiepraam commented
I've been very busy the past few weeks, so couldn't work on this. I think it's right to close this for now as it presented a lot more challenges than I initially thought.

2021-09-30 12:41 UTC, closed without merging