realpath: add -L and -P command-line arguments
uutils/coreutils pull request #2541
Opened 2021-07-31 23:16 UTC by jfinkels

This is my second attempt at adding these, see pull request #2530. (In this one I have tried to minimize the changes to `uucore::fs` to only the changes required to get the new features to work.)

Partially resolves issue #2253.

This pull request adds the `-L` (logical) and `-P` (physical) command-line arguments to `realpath`. The `-L` option makes the program resolve ".." components before symbolic links. The `-P` option makes the program resolve symbolic links as they are encountered. This also changes the default behavior of `realpath` from the `-L` behavior to the `-P` behavior. This matches the behavior of GNU `realpath`. I don't fully understand all the things that `-L` is supposed to do, but this is a start, and seems to match the basic tests in the GNU coreutils test suite.

2021-08-06 11:10 UTC, sylvestre commented
I guess you saw that some of the windows tests are failing
```

    test_realpath::test_logical
    test_realpath::test_logical_overrides_physical
    test_realpath::test_physical
    test_realpath::test_physical_default
    test_realpath::test_physical_overrides_logical
```

2021-08-12 23:38 UTC, sylvestre requested changes
needs tests to be fixed

2021-08-21 00:20 UTC, miDeb commented
Well... I just merged https://github.com/uutils/coreutils/pull/2459 which basially implemented the same feature. I wasn't aware that this PR existed as well. Is there a difference in functionality between this PR and the other one? Maybe we can at least keep the tests from this PR.

2021-08-21 21:10 UTC, jfinkels commented
> Is there a difference in functionality between this PR and the other one? Maybe we can at least keep the tests from this PR.

I don't think there is a difference in functionality. It looks like that other pull request was able to resolve the Windows issues I was having here. The only additional test cases in this pull request are for `-L` overriding `-P`, and vice versa, which doesn't seem all that valuable. But I can add them in a new pull request if desired. Otherwise, I'm just going to close this.

2021-08-21 21:10 UTC, closed without merging