seq: use stdout.write_all() instead of print!()
uutils/coreutils pull request #2647
Opened 2021-09-10 02:15 UTC by jfinkels

Change from using `print!()` to using `stdout.write_all()` in order to allow the main function to handle broken pipe errors gracefully.

I've duplicated a helper function from `test_yes.rs` in order to write the two unit tests. A future change can refactor them.

One feature our version of `seq` does not yet support is `seq 0 inf 1`: we output `NaN` while GNU outputs `0`. I'll create a new issue for that.

2021-09-10 02:16 UTC, jfinkels commented on src/uu/seq/src/seq.rs
> +            stdout.write_all(value.to_string().as_bytes())?;
Is this the right thing to do? `value` is a `BigInt`.

2021-09-10 06:02 UTC, blyxxyz requested changes
Nice change! This is something a lot of utilities need to handle better.

2021-09-11 00:01 UTC, jfinkels commented
I have updated this pull request to use `write!(stdout, ...)` instead of `stdout.write_all()`.

2021-09-13 16:34 UTC, merged

2021-09-13 16:34 UTC, miDeb commented
Thanks! I thought we handled those cases with a panic hook that ignores all "Broken Pipe" errors (`uucore/mods/panic.rs`). However, it's very fragile because the error messages can vary and it only checks if it contains `BrokenPipe`, but it should also check for `Broken pipe` (I actually broke that a while ago...). Could you fix that as well?

2021-09-14 02:07 UTC, jfinkels commented
I would like to help but I don't fully understand what you are suggesting, mostly because I am new to Rust. If you are just suggesting making a small change to this line of code, then I can do that: https://github.com/uutils/coreutils/blob/e9d63519dd7288f320c7e1074a67243a2aedb09a/src/uucore/src/lib/mods/panic.rs#L11

2021-09-14 18:08 UTC, miDeb commented
@jfinkels yeah that's what I was trying to suggest. Also, I'm surprised to hear that you are new to rust given the high quality of your contributions :)

2021-09-15 01:03 UTC, jfinkels commented
Thank you. Although I am new to Rust, I am not new to software development :+1: I'll make the change you suggest in a new pull request.

2021-09-15 01:28 UTC, jfinkels commented
https://github.com/uutils/coreutils/pull/2683