printf - Update %g formatting to match GNU
uutils/coreutils pull request #3087
Opened 2022-02-06 22:56 UTC by water-ghosts

Resolves #2775. 

This format is unintuitive. Uutils previously had `%g` return either the standard `%f` output or scientific notation, whichever was shorter. This seems to be a common summary of the format, but it doesn't fully explain its behavior. For example, `printf %g 1.234567` prints `1.23457`, while `%f` prints `1.234567`.  

This PR changes the definition to apply three rules:
1) Choose scientific notation or float notation based on the number's magnitude, not its length.
2) Round to 6 significant figures.
3) Remove trailing zeroes.

I’ve added several tests to validate these rules, and confirmed that GNU gives the same results for each test. 

There are probably better ways to write some of this string parsing. I’m still a bit perplexed by Rust’s complex string rules, so I’d appreciate any feedback or cleanup!

2022-02-08 03:12 UTC, water-ghosts commented
Any idea why `test_dd::test_final_stats_unspec` is failing for the Windows build? I ran the test suite locally on Windows 10 and everything passed.

2022-02-21 15:08 UTC, jfinkels reviewed
I restarted the CI tests, they seem to all pass, so that's great.

It's a bit tough to follow the logic, like you imply in the description. Perhaps some comments, documentation, and/or examples to go with the helper functions would make it easier to understand?

2022-03-03 21:34 UTC, sylvestre requested changes
Just like @jfinkels said (more comments :)

2022-03-11 22:43 UTC, sylvestre commented
@water-ghosts ping?

2022-03-21 04:49 UTC, water-ghosts commented
I've added comments and renamed some variables. Hopefully it's clearer :)

2022-03-21 12:18 UTC, jfinkels approved these changes
Great!

2022-03-21 12:23 UTC, merged