reduce the nesting of a couple of match statements
uutils/coreutils pull request #3273
Opened 2022-03-19 15:33 UTC by anastygnome

2022-03-19 15:44 UTC, tertsdiepraam requested changes
Thanks for rebasing it! In the future you can just (force) push the rebased branch to the original PR. I think the rebasing of hashsum introduced some mistakes though, could you take a look at that?

2022-03-19 15:44 UTC, tertsdiepraam commented on src/uu/hashsum/src/hashsum.rs
> +use md5::Context as Md5;
I think this has recently changed and should be kept how it is now.

2022-03-19 15:44 UTC, tertsdiepraam commented on src/uu/hashsum/src/hashsum.rs
> +        Ok(bytes.to_hex())
Same here

2022-03-19 15:45 UTC, anastygnome commented on src/uu/hashsum/src/hashsum.rs
> +        Ok(bytes.to_hex())
will co

2022-03-19 15:52 UTC, anastygnome commented
@tertsdiepraam Do you want me to squash that ?

2022-03-19 16:17 UTC, tertsdiepraam commented
It's fine to just add a commit to fix it

2022-03-19 17:14 UTC, anastygnome commented
@tertsdiepraam it's all good

2022-03-19 17:42 UTC, tertsdiepraam requested changes
I found a few more issues with hashsum. Sorry that this took long to merge and caused conflicts :)

2022-03-19 17:42 UTC, tertsdiepraam commented on src/uu/hashsum/src/hashsum.rs
> -        ("b3sum", "work with BLAKE3"),
and here

2022-03-19 17:42 UTC, tertsdiepraam commented on src/uu/hashsum/src/hashsum.rs
> -            | "b3sum"
This should not be removed

2022-03-19 17:42 UTC, tertsdiepraam commented on src/uu/hashsum/src/hashsum.rs
> -        ),
Same here

2022-03-19 17:54 UTC, anastygnome commented
@tertsdiepraam it should now be all set

2022-03-19 21:58 UTC, sylvestre commented
Looks like it doesn't work:
```

---- test_hashsum::b3sum::test_check stdout ----
current_directory_resolved: 
run: /home/runner/work/coreutils/coreutils/target/debug/coreutils hashsum --b3sum --bits=256 --check b3sum.checkfile
thread 'test_hashsum::b3sum::test_check' panicked at 'Command was expected to succeed.
stdout = 
 stderr = hashsum: You must specify hash algorithm!
', tests/common/util.rs:174:9

```

2022-03-25 22:16 UTC, sylvestre commented
ping?

2022-04-12 12:38 UTC, sylvestre commented
ping?

2022-04-25 21:10 UTC, sylvestre commented
Closed
please reopen when ready

2022-04-25 21:10 UTC, closed without merging

2022-04-30 13:42 UTC, anastygnome commented
won't be able to fix this, this is beyond my ability