install: verbose - list all created directories
uutils/coreutils pull request #3420
Opened 2022-04-17 22:33 UTC by sylvestre

```
$ install -Dv source_file1 sub3/a/b/c/file
install: creating directory 'sub3'
install: creating directory 'sub3/a'
install: creating directory 'sub3/a/b'
install: creating directory 'sub3/a/b/c'
'source_file1' -> 'sub3/a/b/c/file'
```

Necessary step for tests/install/basic-1.sh

2022-04-18 08:58 UTC, tertsdiepraam requested changes
There's a slightly different behaviour in GNU. If I create the directories `sub3` and `sub3/a` first, then the output should be: 
```
❯ install -Dv source_file1 sub3/a/b/c/file
install: creating directory 'sub3/a/b'
install: creating directory 'sub3/a/b/c'
'source_file1' -> 'sub3/a/b/c/file'
```

2022-04-18 12:58 UTC, sylvestre commented
Oh, smart, thanks :)

2022-04-18 20:14 UTC, sylvestre commented
I think i did it :)

2022-04-19 16:55 UTC, tertsdiepraam approved these changes

2022-04-19 16:56 UTC, merged