cp: use sparse copy on --sparse=always
uutils/coreutils pull request #4030
Opened 2022-10-12 00:42 UTC by jfinkels

Correct the behavior of `cp --reflink=never --sparse=always` so that it performs a sparse copy. Before this commit, it was incorrectly performing a dense copy.

This should cause the GNU test suite file `tests/cp/sparse.sh` to pass.

2022-10-12 07:23 UTC, sylvestre commented
side note, i love the bot. Many thanks @tertsdiepraam :)

2022-10-12 07:24 UTC, sylvestre commented
@jfinkels would it be possible to have a test or it is too hard?
thanks

2022-10-22 08:20 UTC, sylvestre requested changes
needs a test

2022-10-23 03:50 UTC, jfinkels commented
I have added a test

2022-11-11 07:43 UTC, merged

2022-11-11 08:12 UTC, sylvestre commented
congrat :)