sort: Allow percentages as values for buffer-size
uutils/coreutils pull request #4059
Opened 2022-10-18 17:40 UTC by sallto

Fixes issue uutils#3500 by adding support for percentags of total memory for the buffer-size flag. The sysinfo crate is used to determine the total memory of a system.

I used the sysinfo crate instead of hacking together unsafe code to work with libc. This makes the changed part crossplatform-compatible and realistically safer since sysinfo is a well maintained and actively developed library.

I used the error handling from the original code. The original program will default to using all of the memory of a system (not just available), while this implementation will panic with an error.

lmk if there are weird things I did as this is my first "production" rust code. Thanks!

2022-10-18 18:48 UTC, sylvestre commented on src/uu/sort/src/sort.rs
> +use sysinfo::{RefreshKind, System, SystemExt};
Would it be possible to do the same with a crate that we already using?
AFAIK, we aren't using sysinfo currently

2022-10-19 09:24 UTC, sylvestre commented
Thanks
could you please add an integration test here https://github.com/uutils/coreutils/blob/main/tests/by-util/test_sort.rs too?

2022-10-19 10:22 UTC, sallto commented
Added the tests!
FYI: The nix crate understandably breaks the macos build. With the sysinfo crate this worked. I don't know if this is a priority

2022-10-22 08:20 UTC, sylvestre commented
yeah, it is a priority to keep all jobs green, sorry :)

2022-10-26 10:44 UTC, sallto commented
Ok I rewrote that part with platform-specific code. I had to disable some tests on 32-bit since the CI/CD Pipeline has more than 2^32 bit of total ram.

2022-11-07 14:34 UTC, sallto commented
What are the next steps now? I restarted the CI pipeline on the branch which made the macos build pass. So only the android test job fails (which it also does on them main branch). See https://github.com/sallto/coreutils/actions/runs/3383769224

2023-03-27 19:00 UTC, sylvestre requested changes
needs to be rebased

2023-04-28 07:25 UTC, sylvestre commented
@sallto ping?

2023-06-20 21:30 UTC, sylvestre commented
no action for a while, closing.

2023-06-20 21:30 UTC, closed without merging