mv: add progress bar
uutils/coreutils pull request #4220
Opened 2022-12-07 13:59 UTC by ctsk

Similarly to `cp`, adds `-g` and `--progress` flags to enable a progress bar via indicatif.

The logic is tricker than the progress bar logic in `cp` and modeled closely to  the implementation in advcpmv. In particular, the progress bar does not calculate the total size of the files if the move is performed via a rename operation. To still show adequate feedback, we use two progress bars:

1. Count-Progress-Bar
  - This progress bar indicates how many of the source arguments have been moved. 
  - Only shows up if there's 2 or more source arguments

2. Folder-Copy-Progress-Bar
  - This progress bar indicates how much of a folder has been moved.
  - Only shows up if the source is a folder and copy+remove is required. Doesn't show up for file copies, as there's no progress reporting for that.

<details>
<summary>Screenshots</summary>

Multiple a file and a folder are mv'd across filesystems:

![Screenshot from 2022-12-07 14-47-03](https://user-images.githubusercontent.com/9384305/206197384-908bac34-d437-4237-8047-283c3fb6c0b8.png)

![Screenshot from 2022-12-07 14-47-07](https://user-images.githubusercontent.com/9384305/206197375-e8da95f7-6e25-416a-ac6b-5aa4071f5e01.png)

</details>

2022-12-07 19:25 UTC, tertsdiepraam requested changes
Excellent! I really like this design. My only important suggestion is that we can simplify the logic around the `MultiProgress`, by always initializing one if the progress bar flag is passed. Then we can always just add to it instead of having to branch between a `MultiProgress` and a single `ProgressBar`.

It's a bit unfortunate that we have to take `suspend` into account for all the prints, but I don't have a solution for that :)

2022-12-07 19:25 UTC, tertsdiepraam commented on src/uu/mv/src/mv.rs
> +            };
I think I prefer something like this to make it a bit simpler in my opinion:
```rust
let result = if let Some(ref pb) = progress_bar {
    move_dir_with_progress(from, to, &options, |process_info| {
        pb.set_position(process_info.copied_bytes);
        pb.set_message(process_info.file_name);
        TransitProcessResult::ContinueOrAbort
    })
} else {
    move_dir(from, to, &options)
}
```

2022-12-07 19:25 UTC, tertsdiepraam commented on src/uu/mv/src/mv.rs
> +            };
```suggestion
            let total_size = dir_get_size(from).ok();
```

2022-12-07 19:25 UTC, tertsdiepraam commented on src/uu/mv/src/mv.rs
> +                    }
I think we can simplify this logic, by always making a `MultiProgress` if `b.progress_bar` is `true`. Just with either zero or one bar already in it. Then we only have to match on `multi_progress` and check `b.progress_bar` anymore.

2022-12-07 19:25 UTC, tertsdiepraam commented on src/uu/mv/src/mv.rs
> +    get_size as dir_get_size, move_dir_with_progress, CopyOptions as DirCopyOptions,
Cool! We might want to look into using that same `get_size` function in `cp` as well (in another PR).

2022-12-08 17:30 UTC, ctsk commented
Thank you for all the feedback!

2022-12-13 10:46 UTC, tertsdiepraam approved these changes
Looks good! Thanks!

2022-12-13 10:46 UTC, merged