Require = for --tmpdir in mktemp
uutils/coreutils pull request #4342
Opened 2023-02-11 06:38 UTC by tmccombs

Fixes #3454

This implementation more closely matches the behavior of GNU mktemp. Specifically, if using the short-form `-p`, then DIR is required, and if using the long form `--tmpdir` then DIR is optional, but if provided, must use the `--tmpdir=DIR` form (not `--tempdir DIR`), so that there is no ambiguity with also passing a TEMPLATE.

The downside to this implementation is we are now introducing a new workaround for https://github.com/clap-rs/clap/issues/4702 where we use separate calls to `.arg()` for the short `-p` and the long `--tmpdir`, which results in a less than ideal output for `--help`.

2023-02-11 08:03 UTC, tertsdiepraam commented
Cool! Did you see #4275 already? Is this an improvement over that PR?

2023-02-12 08:16 UTC, tmccombs commented
I didn't see that other PR. I'm doing a review of it now. Overall, it looks pretty similar.

2023-02-12 14:52 UTC, tertsdiepraam commented
I commented the same on the other PR, but I like the approach here a bit better, as long it passes the same tests. So you could copy the tests from that PR (maybe with a co-author credit to @dmatos2012 in the commit).

2023-02-13 08:55 UTC, dmatos2012 commented
Hey @tmccombs @tertsdiepraam , yes I also think this PR is slightly cleaner with the `override_with()` clap argument, and mine is for sure older, so fine by me to use this one, but I would like indeed if the tests that I wrote I used that I get the co-author like @tertsdiepraam mentioned. 

So good job, looking nice :)

2023-02-13 10:25 UTC, tertsdiepraam commented
I just see that you've also opened an issue at clap. If they want this functionality that's fine, but I don't think we need to push for this feature and complicate clap unnecessarily. For context, I've been working on a custom argument parser for uutils (see https://github.com/uutils/coreutils/issues/4254). This is what `mktemp` looks like in that parser: https://github.com/tertsdiepraam/uutils-args/blob/main/tests/coreutils/mktemp.rs

2023-03-27 19:19 UTC, sylvestre requested changes
Still draft

2023-04-02 10:39 UTC, tertsdiepraam commented
Looks good! From my perspective, all that's missing is a co-author credit for @dmatos2012 in the test commit.

2023-06-20 21:41 UTC, sylvestre requested changes
could you please fix the conflict? thanks

2023-07-05 10:52 UTC, tertsdiepraam commented
I'm trying to fix the test on windows to get this merged finally :)

2023-07-21 12:36 UTC, merged

2023-07-21 12:36 UTC, sylvestre commented
well done!