`hashsum`: add `--zero`  option (#4612)
uutils/coreutils pull request #4632
Opened 2023-03-25 11:08 UTC by 0xMRTT

2023-03-25 12:02 UTC, 0xMRTT commented
@tertsdiepraam Made a dumb error, now that's should be good...

2023-03-25 12:14 UTC, sylvestre commented
Could you please add a test?

2023-03-25 15:07 UTC, sylvestre commented on tests/by-util/test_hashsum.rs
>                  .no_stderr()
Please run rustfmt on the test too

2023-03-27 20:53 UTC, sylvestre requested changes
needs rustfmt

2023-03-28 21:26 UTC, merged