tsort: Switch to BTreeHash and BTreeSet
uutils/coreutils pull request #4931
Opened 2023-06-02 18:59 UTC by cazou

Using HashMap and HashSet give a valid topological sort, but the output will change randomly at each run.

BTree based structures will guarantee that the output is always ordered in the same way.

This also makes the ouptut similar to the output of the C version of the tools, on which some applications rely.

An example of application that rely on this is the `initramfs-update` program on Debian that uses `tsort` to create the order of hooks execution. The floating nodes still need to be executed alphabetically to avoid having the `busybox` version of some tools in `initramfs` instead of the full versions. See [this issue](https://gitlab.apertis.org/infrastructure/apertis-issues/-/issues/334#note_100371) on Apertis.

Although the issue could be fixed in `initramfs-update`, other tools/programs could rely on this ordered output and a stable output for a given input makes sense.

2023-06-03 08:39 UTC, sylvestre commented
oh, super interesting.
could you please add a test to make sure we don't regress in the future ? thanks

2023-06-03 11:52 UTC, tertsdiepraam commented
While I think we should merge this because correctness is more important than speed, I was curious what the performance difference would be and this seems to make `tsort` twice as slow[1]. I bet there would be some people interested in figuring out how to speed this up if we open an issue for it.


[1]: On a test case generated with this Python script:
```python
import random

N = 10000
for i in range(100*N):
    a = random.randint(0,N)
    b = random.randint(0,N)
    if a != b:
        print(f"{min(a, b)} {max(a, b)}")
```

2023-06-04 16:47 UTC, sylvestre requested changes
needs a test

2023-06-05 04:59 UTC, anastygnome commented
Although this PR fixes the correctness issue, wouldn't it be better to use a graph library such as [petgraph](https://github.com/petgraph/petgraph) that supports topological sort ? (MIT-licensed) 

Maybe we would get better performance

2023-06-05 08:28 UTC, tertsdiepraam commented
Maybe, but since this is a very small PR, we can accept this first and optimize later.

2023-06-05 19:26 UTC, cazou commented
Any idea why `inotify-dir-recreate` would fail ?

2023-06-05 19:54 UTC, sylvestre commented
unrelated
we have an intermittent issue on this one :(

2023-06-05 20:33 UTC, merged