`printf`: support %q
uutils/coreutils pull request #5472
Opened 2023-10-29 14:33 UTC by Luv-Ray

fix #5468 
Now `printf %q '"$test"'` can produce the right result:
```
./target/debug/printf %q '"$test"'; echo
\"\$test\"
```
However I have a doubt about the description in [GNU manual](https://www.gnu.org/software/coreutils/manual/coreutils.html#printf-invocation):
> An additional directive `%q`, prints its argument string in a format that can be reused as input by most shells. Non-printable characters are escaped with the POSIX proposed `$''` syntax, and shell metacharacters are quoted appropriately. This is an equivalent format to ls --quoting=shell-escape output.

And in my local:
```
$ ls --quoting=shell-escape
'"$test"'
$ printf %q '"$test"'; echo
\"\$test\"
```
What does "equivalent format" mean?

2023-10-30 13:41 UTC, tertsdiepraam requested changes
That is indeed curious. This does seem to give the same output as `ls`. I think `echo` might be doing the escaping in your example:
```
env printf %q '"$test"'
```
I'd like this to use the same function as in `ls` because we have a pretty good robust implementation of it there. The implementation of it is here: https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/quoting_style.rs

Note too that there is a little spelling error (the word "metacharacters" needs to be ignored).

2023-11-02 07:47 UTC, Luv-Ray commented
Sorry for the mistake, actually I'm not using the GNU's printf when I directly call `printf`, which has made me confused.
```
$ printf %q '$'; echo
\$
$ /usr/bin/printf %q '$'; echo
'$'
$ env printf %q '$'; echo
'$'
```
There is an `echo` because `printf` doesn't add an `\n` at the end of the output, and It's not the cause of the difference between commands.

2023-11-02 13:03 UTC, tertsdiepraam reviewed
Looking good, thanks! Accidentally using the shells `printf` happens to me all the time too 😄

2023-11-02 13:03 UTC, tertsdiepraam commented on src/uucore/src/lib/features/tokenize/sub.rs
> +                                    Some(max) => String::from(&arg_string[..max as usize]),
Could you maybe add a test for this case?

2023-11-02 15:13 UTC, tertsdiepraam commented on src/uucore/src/lib/features/tokenize/sub.rs
> +                                    Some(max) => String::from(&arg_string[..max as usize]),
Nice!

2023-11-02 15:17 UTC, Luv-Ray commented on src/uucore/src/lib/features/tokenize/sub.rs
> -                    self.text_so_far.push(ch);
This unnecessary push cause wrong error message: `printf: %7bb invalid conversion specification\n`, which has one more `b`.

2023-11-09 02:11 UTC, closed without merging