cp --link: don't fail if destination is hardlink to source
uutils/coreutils pull request #5484
Opened 2023-11-01 09:48 UTC by cakebaker

With this PR, `cp --link` no longer shows a "same file" error if the destination is a hardlink to the source.

2023-12-25 12:03 UTC, sylvestre commented
@cakebaker still draft?

2023-12-25 13:51 UTC, cakebaker commented
As the GNU tests pass I think this PR shouldn't be a draft anymore.

2023-12-25 21:20 UTC, sylvestre commented
@cakebaker doesn't pass anymore it seems
```

2023-12-25T13:17:22.7079283Z mkdir: d00000000000000000000000001e+04: File exists
2023-12-25T13:17:22.7079415Z mkdir: d00000000000000000000000001e+04: File exists
2023-12-25T13:17:22.7079777Z link-heap.sh: set-up failure: 
2023-12-25T13:17:22.7079988Z ERROR tests/cp/link-heap.sh (exit status: 99)
```

2023-12-25 21:23 UTC, sylvestre requested changes
.

2023-12-26 07:22 UTC, cakebaker commented
I think it is an unrelated issue, it is also shown with other PRs.

2023-12-26 15:12 UTC, merged