sort: allow `-f` to be pass multiple time
uutils/coreutils pull request #5681
Opened 2023-12-20 02:41 UTC by just1602

Hello :wave: 

This small PR try to fix #5667.

I'm pretty new to rust, so if there's a better way to allow a flag to be pass multiple time, let me know.  :smile:

2023-12-20 09:22 UTC, tertsdiepraam commented
Thanks! Yeah, there is a better way, although you would've needed to know `clap` pretty well to find it 😄 You can check out this PR as an example: https://github.com/uutils/coreutils/pull/5671. As a bonus it will work for all arguments if we do it that way.

2023-12-20 09:24 UTC, tertsdiepraam requested changes
See comment above

2023-12-20 14:19 UTC, sylvestre commented
and with a test to make sure we don't regress please :)

2023-12-21 09:09 UTC, tertsdiepraam approved these changes
Excellent!

2023-12-21 09:09 UTC, merged