Csplit: Add missing precision syntax
uutils/coreutils pull request #5794
Opened 2024-01-05 22:38 UTC by spineki

# Summary
This pull request adds support for the `precision` syntax in Csplit filename-suffix patterns (`-b` flag).

example: to create files were the suffix is 10-elements long, padded to the left (-), with 3-digit precision (.3) in lower hex "x"
```
csplit -b 'cst-%-10.3x-' in 1
```

Additionally, it allows using `#`, `0` flags at the same time.
Csplit allows split files to be named with fixed precision, independent from outer width.

## Remarks
C and Rust format syntaxes differ when dealing with zero precision, octal prefix or precision in case of alternative mode (C doesn't take the extra 0x or o into account while rust does). This is why I did not follow the initial exhaustive match approach and opted for grouping cases as much as possible.

To avoid redundant code, I split the extraction in two formatting steps. First, creating the inner formatted number, with a length of `precision`, then, adding additional padding, filling and direction for a total lenght of `width`.

There are a lot of corner cases, don't hesitate to point something I may have missed !

## Related Issue
https://github.com/uutils/coreutils/issues/5709

## Tests
I added additional tests to check patterns involving multiple flags or single-dot-precision syntax.
I modified some tests because octal notation is not formatted the same way in rust or in C. (0 in front of `n` in C, `o` in front of `n` in Rust)

2024-01-06 21:28 UTC, sylvestre commented
Could you please add an integration test in tests/by-util/test_csplit.rs ?
thanks

2024-01-08 09:22 UTC, tertsdiepraam requested changes
Nice work! This looks pretty good, but unfortunately duplicates a lot of the `printf` style formatting that is also present in other utils. If we keep separate implementations, we end up with incompatibilities and code that is hard to maintain.

The GNU docs say:

> Use format as the output file name suffix. When this option is specified, the suffix string must include exactly one printf(3)-style conversion specification, possibly including format specification flags, a field width, a precision specification, or all of these kinds of modifiers. The format letter must convert a binary unsigned integer argument to readable form. The format letters ‘d’ and ‘i’ are aliases for ‘u’, and the ‘u’, ‘o’, ‘x’, and ‘X’ conversions are allowed. The entire format is given (with the current output file number) to sprintf(3) to form the file name suffixes for each of the individual output files in turn. If this option is used, the --digits option is ignored. 

Source: https://www.gnu.org/software/coreutils/manual/html_node/csplit-invocation.html

So instead of reimplementing it, we should probably use our `printf` code. In particular, you could look how the printing code in `seq` is implemented. I think that is very similar, apart from the fact that we're printing integers instead of floats here.

See the `seq` code here:

https://github.com/uutils/coreutils/blob/8e83b347c6bdeb91e332d696fdb18aaece2db2b3/src/uu/seq/src/seq.rs#L111-L117

And the corresponding code from our formatting code:

https://github.com/uutils/coreutils/blob/8e83b347c6bdeb91e332d696fdb18aaece2db2b3/src/uucore/src/lib/features/format/mod.rs#L290

Sorry, I wish we could have alerted you sooner about that functionality! Nevertheless, the tests you've made will be very useful to see if the `printf` version actually works!

2024-01-08 11:20 UTC, spineki commented
Thanks for the insights !

I tested the existing `printf` features to see if I could rely on it.

However
```c
#include <stdio.h>

int main()
{
    printf("before %#15.6o after", 42);
    return 0;
}

gives:
before    052 after
```

```sh
cargo run printf "before %#15.6o after", 42
before          0o52   after
gives
```
current formatting 
- doesn't handle precision (.3) (makes sense for the current issue)
- doesn't handle octal prefix (`o` instead `0`)
- something is wrong with the spacing (three spaces after 52 instead of 1)

I may have missed something, but from what I see, the uucore/src/lib/features/format would need deeper changes to correct both printf and csplit implementation.

2024-01-08 11:37 UTC, tertsdiepraam commented
Nice find! You're right about those incompatibilities, but we should fix those in `printf`!

By the way, I get this from both GNU `printf` in the terminal and `printf` in C:
```
before          000052 after
```

Maybe we could open separate issues for each of these problems.

2024-02-04 15:20 UTC, tertsdiepraam commented
@spineki, I'm gonna close this since I think we agree this should be handled by the `printf` mechanisms we already have. Feel free to open a new PR for that. Thanks for helping us find the issues with `printf`!

2024-02-04 15:21 UTC, closed without merging

2024-02-07 11:15 UTC, tertsdiepraam commented
Where were we with fixing the `printf` issues?

We've had:
- https://github.com/uutils/coreutils/pull/5808