cp: link-deref gnu test fix
uutils/coreutils pull request #6378
Opened 2024-05-07 16:12 UTC by matrixhead

2024-05-07 18:51 UTC, BenWiederhake requested changes
LGTM, except that one typo. (I understand that the typo is also present in the already-existing code; feel free to keep it or fix it as you see fit.)

(Remaining CI failures are known issues #6275 and #6333, so out of scope for this PR.)

Before I merge this, I want to give the other maintainers an opportunity to look at it, because I don't feel 100% confident around symlinks. But this seems  very reasonable.

2024-05-07 18:51 UTC, BenWiederhake commented on tests/by-util/test_cp.rs
> +                assert_eq!(src_ino, dest_ino,);
```suggestion
                assert_eq!(src_ino, dest_ino);
```

2024-05-08 05:46 UTC, matrixhead commented on tests/by-util/test_cp.rs
> +                assert_eq!(src_ino, dest_ino,);
okay, I will do it thanks

2024-05-08 13:30 UTC, BenWiederhake approved these changes
LGTM. I'll wait for a few days for the others too look at it, because I don't feel 100% confident around the symlink code.

2024-05-08 16:08 UTC, matrixhead commented
is it because I tried to squeeze in deref logic into parsing code

2024-05-19 08:14 UTC, merged

2024-05-19 08:15 UTC, sylvestre commented
well done!