tr: Raise error if set2 is too big on complemented class
uutils/coreutils pull request #6564
Opened 2024-07-12 14:15 UTC by RenjiSann

Fixes #6345

2024-07-14 21:33 UTC, BenWiederhake requested changes
The code change itself is great! It's really straight-forward, thanks to the previous PRs.

I have some requests about the test: Please test the positive case, fix a technically-incorrect comment, and make sure the test checks for the correct failure reason. (Details below.)

2024-07-14 21:33 UTC, BenWiederhake commented on tests/by-util/test_tr.rs
> +    let x231 = "x".repeat(231);
The existence of this test is great! Can you also add a test to make sure that using 230 works as intended?

2024-07-14 21:33 UTC, BenWiederhake commented on tests/by-util/test_tr.rs
> +    // [:upper:] expands to 230 characters, putting more characters in set2
```suggestion
    // The complement of [:upper:] expands to 230 characters, putting more characters in set2
```

2024-07-14 21:33 UTC, BenWiederhake commented on tests/by-util/test_tr.rs
> +        .fails();
Please also check whether the "correct" error message has been generated. (Just in case this invocation fails for an unrelated reason.)

2024-07-15 08:05 UTC, RenjiSann commented
Force push fixed this:
- Add `The complement of` ('[:upper:]').
- Add a test with 230 x.
- Check the expected error message

2024-07-15 15:55 UTC, BenWiederhake approved these changes
Code looks good to me, tests both the positive and the negative case, remaining failures are unrelated issues with CI: #6534, #6569, #6570 (twice).

2024-07-15 15:55 UTC, merged