ls: Fix unknown IO error
uutils/coreutils pull request #6744
Opened 2024-09-27 15:55 UTC by rulu158

From #6710 (explanation [here](https://github.com/uutils/coreutils/issues/6710#issuecomment-2379596742)).

2024-09-27 15:58 UTC, sylvestre commented
please add a test to make sure we don't regress

2024-09-30 07:41 UTC, sylvestre requested changes
needs a test

2024-10-01 21:59 UTC, rulu158 reviewed
Tests added.

2024-10-02 07:21 UTC, sylvestre commented
>  CICD / Build (ubuntu-latest, i686-unknown-linux-musl, feat_os_unix_musl, use-cross) (pull_request) Failing after 6m 

one of the tests fails. Maybe just skip it for musl

2025-02-16 23:20 UTC, sylvestre commented
sorry, it needs to be rebased :/

2025-02-24 01:36 UTC, RenjiSann commented
ping @rulu158

2025-04-17 20:01 UTC, sylvestre commented
please reopen when ready

2025-04-17 20:01 UTC, closed without merging