uucore/buf_copy: bug fixes for compatibility with uutils core utilities
uutils/coreutils pull request #6983
Opened 2024-12-20 05:15 UTC by DaringCuteSeal

This PR addresses several issues that previously hindered the usage of the new buffer-based copying module (#6964) in several core utilities (notably `cp`, `cat`, `yes`, and `install`).

2024-12-20 07:48 UTC, sylvestre commented on src/uucore/src/lib/features/buf_copy.rs
> +#[cfg(any(target_os = "linux", target_os = "android"))]
it is starting to look messy with all the cfg
maybe the .rs file per platform ?
for example:
src/uu/tail/src/platform/

2024-12-22 18:08 UTC, sylvestre requested changes
needs some refactoring. Too many cfg

2024-12-22 23:48 UTC, DaringCuteSeal commented
oh right on that, wait

2024-12-25 00:58 UTC, DaringCuteSeal commented
@sylvestre how's it

2024-12-28 11:53 UTC, sylvestre commented on src/uucore/src/lib/features/buf_copy.rs
> +    };
```suggestion
    #[cfg(unix)]
    {
    use crate::pipes;
    use std::fs::OpenOptions;
    use std::{
        io::{Seek, SeekFrom},
        thread,
    };
    }
```

2024-12-28 11:53 UTC, sylvestre commented on src/uucore/src/lib/features/buf_copy.rs
> +    };
I think it works :)

2024-12-28 11:53 UTC, sylvestre commented on src/uucore/src/lib/features/buf_copy.rs
> +    #[cfg(any(target_os = "linux", target_os = "android"))]
same change here

2024-12-28 11:54 UTC, sylvestre commented on src/uucore/src/lib/features/buf_copy/common.rs
> +use crate::error::UError;
please add the license header here

2024-12-28 11:54 UTC, sylvestre commented
much better, thanks :)
just a few comments now

2024-12-28 13:39 UTC, DaringCuteSeal commented
there, should be ok now

2024-12-28 14:30 UTC, merged

2024-12-28 14:30 UTC, sylvestre commented
thanks!